insert into events (id,
                    title,
                    artists_id,
                    locations_id,
                    descriptions,
                    occupied_places,
                    age_limit,
                    dates,
                    continuance,
                    price)
values (1,
        'Death Race For Love',
        1,
        1,
        'Dj Khaled a hundred racks, i made another one (uh-huh)',
        15,
        18,
        '2023-07-16',
        '3:00:00',
        150);

insert into events (id,
                    title,
                    artists_id,
                    locations_id,
                    descriptions,
                    occupied_places,
                    age_limit,
                    dates,
                    continuance,
                    price)
values (2,
        'Man On The Moon',
        2,
        1,
        'I will me fine, i get it. I will be coooooooool hmmmm.',
        23,
        21,
        '2023-08-06',
        '3:00:00',
        150);

insert into events (id,
                    title,
                    artists_id,
                    locations_id,
                    descriptions,
                    occupied_places,
                    age_limit,
                    dates,
                    continuance,
                    price)
values (3,
        'OPS WANT ME DEAD',
        3,
        1,
        'Live your life like we die in the world space. Fell so right.',
        15,
        18,
        '2023-12-16',
        '3:00:00',
        150);
